# Generated by Django 6.1.1 on 2026-09-03 22:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "directory_address",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("is_local", models.BooleanField(default=False)),
                ("in_admin_group", models.BooleanField(default=False)),
                ("admin_flag", models.BooleanField(default=False)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_sign_in", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.IntegerField()),
                ("changed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SignInAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                ("started", models.DateTimeField(auto_now_add=True)),
                (
                    "last_request",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ended", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "signed out"),
                            ("idle", "idle for too long"),
                            ("elsewhere", "signed in elsewhere"),
                            ("deactivated", "deactivated"),
                            ("blocked", "blocked"),
                            ("admin_ended", "ended by an Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started"],
                "indexes": [
                    models.Index(
                        fields=["user", "ended"], name="core_logins_user_id_15154f_idx"
                    )
                ],
            },
        ),
    ]
