# Generated by Django 6.1.1 on 2026-09-03 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_kind", models.CharField(default="user", max_length=10)),
                ("actor_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "actor_directory_address",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                ("category", models.CharField(db_index=True, max_length=20)),
                ("event", models.CharField(db_index=True, max_length=60)),
                ("outcome", models.CharField(default="success", max_length=10)),
                (
                    "reason_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "affected_user_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "affected_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_label",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("login_session_id", models.BigIntegerField(blank=True, null=True)),
                ("client_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "client_browser",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("chain_version", models.IntegerField(default=1)),
                ("previous_hash", models.CharField(max_length=64)),
                ("row_hash", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["category", "event"], name="core_row_categor_6df2e3_idx"
                    ),
                    models.Index(
                        fields=["actor_user_id"], name="core_row_actor_u_2e22d6_idx"
                    ),
                ],
            },
        ),
    ]
