# Generated by Django 6.1.1 on 2026-09-03 23:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_audit_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_reprocessing", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("original_filename", models.CharField(max_length=400)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "media_state",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("checking", "Checking"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("playback_ready", models.BooleanField(default=False)),
                (
                    "refusal_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("probe", models.JSONField(blank=True, default=dict)),
                ("diarize", models.BooleanField(default=False)),
                ("speakers_exactly", models.IntegerField(blank=True, null=True)),
                ("speakers_between", models.JSONField(blank=True, null=True)),
                ("translate", models.BooleanField(default=False)),
                (
                    "spoken_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("vocabulary", models.JSONField(blank=True, default=list)),
                ("context", models.CharField(blank=True, default="", max_length=500)),
                ("model", models.CharField(blank=True, default="", max_length=40)),
                ("preprocessing", models.CharField(default="standard", max_length=20)),
                ("is_two_channel_call", models.BooleanField(default=False)),
                ("tracks_found", models.IntegerField(default=0)),
                ("tracks_distinct", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="core.batch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Side",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("whole", "the whole recording"),
                            ("channel", "one channel of a two-channel call"),
                            ("track", "one audio track"),
                        ],
                        default="whole",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=40)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sides",
                        to="core.recording",
                    ),
                ),
            ],
            options={
                "ordering": ["recording", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recording", "number"), name="one_number_per_side"
                    )
                ],
            },
        ),
    ]
