# Generated by Django 6.1.1 on 2026-09-03 23:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_batch_recording_side"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("merging", models.BooleanField(default=False)),
                (
                    "failure_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.batch",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.recording",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_job_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("state", models.CharField(default="pending", max_length=20)),
                ("stage", models.CharField(blank=True, default="", max_length=30)),
                ("percent", models.FloatField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("audio_minutes_ahead", models.FloatField(blank=True, null=True)),
                (
                    "failure_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("submitted", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("settings_used", models.JSONField(blank=True, default=dict)),
                ("service_versions", models.JSONField(blank=True, default=dict)),
                ("timings", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.job",
                    ),
                ),
                (
                    "side",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.side"
                    ),
                ),
            ],
            options={
                "ordering": ["side__number"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("task_run", models.CharField(blank=True, default="", max_length=20)),
                (
                    "task_reason",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                ("language_probability", models.FloatField(blank=True, null=True)),
                ("language_mixed", models.BooleanField(default=False)),
                ("detection", models.JSONField(blank=True, default=dict)),
                ("word_timestamps", models.BooleanField(default=False)),
                (
                    "word_timestamps_reason",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.job",
                    ),
                ),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="core.recording",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("text", models.TextField()),
                ("speaker", models.CharField(blank=True, default="", max_length=60)),
                ("words", models.JSONField(blank=True, default=list)),
                (
                    "side",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.side",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="core.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["state"], name="core_job_state_dd734f_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["state"], name="core_run_state_4e645c_idx"),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["transcript", "start"], name="core_segmen_transcr_2ec1fb_idx"
            ),
        ),
    ]
