# Generated by Django 6.1.1 on 2026-09-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_job_run_transcript_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="corrected",
            field=models.BooleanField(default=False),
        ),
    ]
