# Generated by Django 6.1.1 on 2026-09-04 12:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_clip"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended", models.DateTimeField(blank=True, null=True)),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("toggle", "the setting was turned off"),
                            ("restore", "a restore"),
                        ],
                        default="toggle",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-started"],
            },
        ),
        migrations.AddField(
            model_name="recording",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recording",
            name="recording_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_on", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="recording",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recordings",
                to="core.case",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["owner", "name"], name="core_case_owner_i_d5f4e7_idx"
            ),
        ),
    ]
