# Generated by Django 6.1.1 on 2026-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="same_as_other_side",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transcript",
            name="shared_segments",
            field=models.IntegerField(default=0),
        ),
    ]
