# Generated by Django 6.1.1 on 2026-09-05 17:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=80)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="core.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CaseChatTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("citations", models.JSONField(blank=True, default=dict)),
                ("readings", models.JSONField(blank=True, default=list)),
                ("skipped", models.JSONField(blank=True, default=list)),
                ("parts", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("done", "done"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "reason_class",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "reason_detail",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("cut_short", models.BooleanField(default=False)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="core.casechat",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
