# Generated by Django 6.1.1 on 2026-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_case_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="casechatturn",
            name="parts_done",
            field=models.IntegerField(default=0),
        ),
    ]
