# Generated by Django 6.1.1 on 2026-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_snapshot_ok", models.BooleanField(default=False)),
                (
                    "last_snapshot_reason",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "last_snapshot_step",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("last_good_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_size_bytes", models.BigIntegerField(default=0)),
                ("snapshots_held", models.IntegerField(default=0)),
                ("last_drill_at", models.DateTimeField(blank=True, null=True)),
                ("last_drill_ok", models.BooleanField(default=False)),
                (
                    "last_drill_step",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("overdue_said_on", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
