# Generated by Django 6.1.1 on 2026-09-12 21:08, then given its data step by hand.
#
# Phase 4 chapter 6 (v1.51.0): the Digest's parts, the record's change points
# and the camera's stamp on the Transcript, the Summary's digest count and
# stage; and the Cues withdrawn, with the Find moments template that made them.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def drop_the_finder_template(apps, schema_editor):
    """The Find moments template is withdrawn; an office's edited copy goes with it."""
    PromptTemplate = apps.get_model("core", "PromptTemplate")
    PromptTemplate.objects.filter(key="finder").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_video_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moment",
            name="cue_text",
        ),
        migrations.AddField(
            model_name="summary",
            name="digest_parts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summary",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="transcript",
            name="change_points",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="stamp",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DigestPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("span_start", models.FloatField(default=0.0)),
                ("span_end", models.FloatField(default=0.0)),
                ("signature", models.CharField(blank=True, default="", max_length=64)),
                ("text", models.TextField(blank=True, default="")),
                ("moments_used", models.IntegerField(default=0)),
                ("model", models.CharField(blank=True, default="", max_length=120)),
                ("made_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest_parts",
                        to="core.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.DeleteModel(
            name="Cue",
        ),
        migrations.RunPython(drop_the_finder_template, migrations.RunPython.noop),
    ]
