# Generated by Django 6.1.1 on 2026-09-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_digest_and_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="digestpart",
            name="seconds",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="moment",
            name="seconds",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepare_done",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepare_reason",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepare_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepare_state",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepare_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transcript",
            name="prepared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
