# Generated by Django 6.1.1 on 2026-09-14, the data step written by hand.

import hashlib

from django.db import migrations, models

# Every shipped wording each template has carried up to v1.53.0, by the short
# hash the app keeps (prompts.text_hash). A stored copy whose text matches
# one of them was never edited by the office, so it may follow the shipped
# wording from now on; any other copy is the office's own and is left alone.
KNOWN = {
    "standard": ("77493e20d40da8c2", "f76d2d1e0c15c0de"),
    "video": ("2e247929fe7a40eb", "29aa0cb5855e3303", "4ed91dd19571870e"),
    "jail_call": ("05d6764a931302ea",),
    "body_camera": (
        "c7815e388b0aa161",
        "4f92a41fd993cfd1",
        "aa5c4e55f36ddebb",
        "e420ebc4c6b26842",
    ),
    "interview": ("8b9b3615694561bb",),
    "phone_call": ("c139726a47bb696e",),
    "hearing": ("3d40afd97acf18f4",),
    "dictation": ("8f9d3f1bc76a9956",),
    "meeting": ("f6b5d89ac94a5842",),
    "prompt:ground_rules": ("7a65498ab25fbf63",),
    "prompt:chat": ("0db99390974f3bef", "a31c1f00877b1dce"),
    "prompt:suggestions": ("122c6e749064c4d6",),
    "prompt:case_chat": ("0003b7162b10fbfd",),
    "prompt:moment": ("e995c610e187a63d", "e9c80701c0ab577f"),
    "prompt:digest": ("c19b8288923ed5e9", "09bca7a6668b3994"),
}


def text_hash(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def mark_unedited_copies(apps, schema_editor):
    SummaryTemplate = apps.get_model("core", "SummaryTemplate")
    PromptTemplate = apps.get_model("core", "PromptTemplate")
    for row in SummaryTemplate.objects.filter(built_in=True):
        found = text_hash(row.text)
        if found in KNOWN.get(row.key, ()):
            row.shipped_hash = found
            row.save(update_fields=["shipped_hash"])
    for row in PromptTemplate.objects.all():
        found = text_hash(row.text)
        if found in KNOWN.get("prompt:" + row.key, ()):
            row.shipped_hash = found
            row.save(update_fields=["shipped_hash"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_prepared_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="digestpart",
            name="cut_short",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="shipped_hash",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="summarytemplate",
            name="shipped_hash",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="transcript",
            name="digest_splits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(mark_unedited_copies, migrations.RunPython.noop),
    ]
