# Generated by Django 6.1.1 on 2026-09-14 17:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_digest_splits_and_shipped_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="vision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batch",
            name="vision_mail_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="vision_wanted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VisionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                ("why", models.CharField(blank=True, default="", max_length=200)),
                ("state", models.CharField(default="waiting", max_length=10)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("line", models.CharField(blank=True, default="", max_length=200)),
                ("done_mailed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_requests",
                        to="core.case",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vision_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_requests",
                        to="core.recording",
                    ),
                ),
            ],
            options={
                "ordering": ["asked_at"],
            },
        ),
    ]
