# Generated by Django 6.1.1 on 2026-09-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_speaker_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakercheck",
            name="cut_short",
            field=models.IntegerField(default=0),
        ),
    ]
