# Generated by Django 6.1.1 on 2026-10-04 15:26

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_second_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="side_number",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="side_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="also_heard_as",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="CaseTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("term", models.CharField(max_length=120)),
                ("also_heard_as", models.JSONField(blank=True, default=list)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="core.case",
                    ),
                ),
            ],
            options={
                "ordering": ["term"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("term"),
                        models.F("case"),
                        name="one_term_per_name_in_a_case",
                    )
                ],
            },
        ),
    ]
