# Generated by Django 6.1.1 on 2026-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_phase_9_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="summaries",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recording",
            name="summary_wanted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="summary",
            name="overnight",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="summary",
            name="state",
            field=models.CharField(
                choices=[
                    ("queued", "queued"),
                    ("running", "running"),
                    ("done", "done"),
                    ("failed", "failed"),
                    ("tonight", "tonight"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
    ]
