# Generated by Django 6.1.1 on 2026-10-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_phase_9_summaries_tonight"),
    ]

    operations = [
        migrations.AddField(
            model_name="casechatturn",
            name="route",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="casechatturn",
            name="scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="casechatturn",
            name="selection",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
